# Generated by Django 4.2 on 2023-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
